### ISSUE TITLE
Requirements Grading

### ISSUE THREAD

**Issue by zenxha** [zenxha/musicgacha#18]
- [x] Owner Requirements
- [x] Team Roles

**Comment by ashwinbabu888** [comment]
Grading - 1/1

Owner requirements (navbar is a work in progress) - has features required by the sponsor with tangibles such as a bootstrap side navbar, a project theme, etc.

Jobs (linking to GH pages is a work in progress) - everyone has specific jobs based on their role and a thorough plan to make the PBL in the coming weeks.

**Comment by jm1021** [comment]
Anthony Vo is PO, music gotcha.   Anthony asked for intelligent technical features, side bar.  Has assignments, including adding GitHub pages requirements.  Kind of like Fantasy Football with Music and rewards based off of popularity.  Has wire frames.

.95/1
