### ISSUE TITLE
Friday Presentation

### ISSUE THREAD

**Issue by calebkimsd** [zenxha/musicgacha#22]
- Big Idea, Sponsor, Hosting Plan, GitHub license
- WireFrames or Web Page mock ups
- Key Workflow or actions within site. See recent Tweet
- Data and any Data Privacy or Security needed.  For instance between Admin and Users of system.

**Comment by rpeddakama** [comment]
3/3
Presentation was clear and had many tangibles regarding current work done so far, deployment plan, and future ideas to implement with the project owner.
