### ISSUE TITLE
Allen PBL Week 1

### ISSUE THREAD

**Issue by purplebears321** [zenxha/musicgacha#26]
## Scrum Master Score: 5/5
- [x] [Sponsor object](https://zenxha.github.io/musicgacha/sponsor) notes found here, [coding plan](https://zenxha.github.io/musicgacha/technicals) including wireframes and workflows here
- [x] Primarily worked on a [rarity generator](https://github.com/zenxha/musicgacha/blob/main/src/main/java/com/musicgacha/controllers/RandomController.java)
>- [Comments](https://github.com/zenxha/musicgacha/blob/a4885cd57fea7dc379b372fd512e036ea7df71ef/src/main/java/com/musicgacha/controllers/RandomController.java#L21) showed thought process for the code
>- [Tester method](https://github.com/zenxha/musicgacha/blob/a4885cd57fea7dc379b372fd512e036ea7df71ef/src/main/java/com/musicgacha/controllers/RandomController.java#L59-L75) which displayed output in terminal
- [x]  Met Sponsor Objective of rarity establishment through [rarity code](https://github.com/zenxha/musicgacha/blob/main/src/main/java/com/musicgacha/controllers/RandomController.java), coding plan tangibles met with wireframe implementation of [about page](https://github.com/zenxha/musicgacha/blob/main/src/main/resources/templates/homesite/about.html) by Sam
- [x] Code and lecture reflections found [here](https://zenxha.github.io/musicgacha/reflection)

[Crossovered Ticket](https://github.com/zenxha/musicgacha/issues/27)

**Comment by samkoenig9** [comment]
Reasoning for grade
- all work planned for the week was completed
- comments and tester included in code
- sponsor objective and tangibles requirement met
- complete and detailed code reflections
-
