### ISSUE TITLE
AP Week 1, Review 1 Ticket

### ISSUE THREAD

**Issue by calebkimsd** [zenxha/musicgacha#30]
## TEAM MUSIC GACHA: SAM - CALEB  - KOMAY - CHRIS - ALLEN

[Music Gacha Website](https://musicgacha.cf/)

<table>
  <tr>
      <th>Idea</th>
      <th>Tangible</th>
  </tr>
      <td>GH Pages</td>
      <td><a href="https://zenxha.github.io/musicgacha/">Link</a></td>
  <tr>
  <tr>
      <td>Technicals</td>
      <td><a href="https://zenxha.github.io/musicgacha/technicals">Link</a></td>
  </tr>
  <tr>
    <td>Scrum Board</td>
    <td><a href="https://github.com/zenxha/musicgacha/projects/1">Link</a></td>
  </tr>
</table>

**Comment by RohanKoshy** [comment]
Team LebronBots Review
3/3
Glow: Clear wireframe with tangibles and the GitHub scrum board seemed to be active on a weekly basis.

Grow: Presentation a bit bland, attempt to show more tangibles.

**Comment by 4disease** [comment]
Team RedTailHawks
3/3
Glow: Very nice initial layout and design. Website seems to navigate smoothly.
Grow: Could show more visuals like images and text to make the website more appealing

**Comment by HexaDrakon** [comment]
Points: 3/3

Glow #1: Github pages were very detailed and demonstrated clarity and organization.
Glow #2: Nice consideration for customer data.
Glow #3: Deployment is detailed. I mean, most of it looks plagiarized from the nginx website, but it's detailed.

Grow #1: Front page is incomplete. I'm a huge fan of "Square 4", but I also am a fan of, like, finished work.
Grow #2: There isn't a link to your deployed website, which makes it _just a bit_ difficult to find.

**Comment by rpeddakama** [comment]
Team Anti Squirrel Taskforce - 3/3
- Website is very well made with clean CSS
- Github pages is organized and shows deployment plan
- Deployed website not shown
