### ISSUE TITLE
Caleb Kim Tech Talk 0

### ISSUE THREAD

**Issue by calebkimsd** [zenxha/musicgacha#7]
NEW Score: 3.8/5

[Individual GH-Pages](https://calebkimsd.github.io/Tri-3-CSA/)

[replit](https://replit.com/@calebkimsd/Challenge-1#Matrix.java)

**Comment by rpeddakama** [comment]
Score: 3.75/5

Replit does not have user input that allows someone to choose which "game" they want to play.
Some of the challenges like matrix do not print the output in the correct format.
Properly embedded in the Github pages.

**Comment by purplebears321** [comment]
## Score: 4/5
#### Team: 2/2
#### Individual: 2/3
- Navigation: Notes are shown in split up sections within his github page (1/1)
- Test prep plans are also contained on his page, but it is in the same column (0.5/1)
- Links to repl on his ticket, has working algorithms, but menu has only slight modifications, implementation isn't changed too much (0.5/1)
